language: csharp
solution: ToXlsx.sln
install:
  - nuget restore ToXlsx.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ToXlsx.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ToXlsx.Tests/bin/Debug/ToXlsx.Tests.dll