language: csharp
solution: ToXlsx.sln
install:
  - nuget restore ToXlsx.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ToXlsx.sln
  - mono ./testrunner/NUnit.Runners.3.4.1/tools/nunit-console.exe ./ToXlsx.Tests/bin/Debug/ToXlsx.Tests.dll