using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Moq;
using NUnit.Framework;

namespace ToXlsx.Tests
{
    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int YearBorn { get; set; }
    }

    [TestFixture]
    public class ToXlsxTests
    {
        private IList<Person> _personList;

        [SetUp]
        public void Setup()
        {
            _personList = new List<Person>();
            _personList.Add(new Person() { FirstName="Daniel", LastName = "Day-Lewis", YearBorn = 1957 });
            _personList.Add(new Person() { FirstName = "Sally", LastName = "Field", YearBorn = 1946 });
            _personList.Add(new Person() { FirstName = "David", LastName = "Strathairn", YearBorn = 1949 });
            _personList.Add(new Person() { FirstName = "Joseph", LastName = "Gordon-Levitt", YearBorn = 1981 });
            _personList.Add(new Person() { FirstName = "James", LastName = "Spader", YearBorn = 1960 });
        }

        [Test]
        public void ColumnsShouldBeAutoGeneratedIfNoColumnsAreSpecified()
        {
            var package = _personList.ToPackage();
            Assert.AreEqual(3,package.Workbook.Worksheets[1].Dimension.Columns);
        }

        [Test]
        public void RowCountShouldMatchListCountPlusHeaderIfNotTitle()
        {
            var package = _personList.ToPackage();
            Assert.AreEqual(_personList.Count + 1 , package.Workbook.Worksheets[1].Dimension.Rows);
        }

        [Test]
        public void RowCountShouldMatchListCountPlusHeaderPlusOneTitle()
        {
            var package = _personList
                .ToWorksheet("Actors")
                .WithTitle("Actors")
                .ToPackage();
            Assert.AreEqual(_personList.Count + 2, package.Workbook.Worksheets[1].Dimension.Rows);
        }

        [Test]
        public void RowCountShouldMatchListCountPlusHeaderPlusTwoTitles()
        {
            var package = _personList
                .ToWorksheet("Actors")
                .WithTitle("Actors")
                .WithTitle("In the movie Lincoln")
                .ToPackage();
            Assert.AreEqual(_personList.Count + 3, package.Workbook.Worksheets[1].Dimension.Rows);
        }

        [Test]
        public void WorksheetShouldMatchSpecifiedStringColumns()
        {
            var package = _personList
                .ToWorksheet("Actors")
                .WithColumn(x=>x.LastName,"Last Name")
                .ToPackage();
            Assert.AreEqual(1, package.Workbook.Worksheets[1].Dimension.Columns);
            for (var i = 0; i < _personList.Count; i++)
            {
                Assert.AreEqual(_personList[i].LastName,package.Workbook.Worksheets[1].Cells[i+2,1].Value.ToString());
            }
        }

        [Test]
        public void WorksheetShouldMatchSpecifiedIntColumns()
        {
            var package = _personList
                .ToWorksheet("Actors")
                .WithColumn(x => x.YearBorn, "Year Born")
                .ToPackage();
            Assert.AreEqual(1, package.Workbook.Worksheets[1].Dimension.Columns);
            for (var i = 0; i < _personList.Count; i++)
            {
                Assert.AreEqual(_personList[i].YearBorn, package.Workbook.Worksheets[1].Cells[i + 2, 1].Value);
            }
        }

        [Test]
        public void MultipleListsShouldCreateMultipleWorksheets()
        {
            var pre50 = _personList.Where(x => x.YearBorn < 1950).ToList();
            var post50 = _personList.Where(x => x.YearBorn >= 1950).ToList();

            var package = pre50
                .ToWorksheet("< 1950")
                .NextWorksheet(post50, "> 1950")
                .ToPackage();

            Assert.AreEqual(2, package.Workbook.Worksheets.Count);
            Assert.AreEqual(pre50.Count+1,package.Workbook.Worksheets[1].Dimension.Rows);
            Assert.AreEqual(3, package.Workbook.Worksheets[1].Dimension.Columns);
            Assert.AreEqual(post50.Count + 1, package.Workbook.Worksheets[2].Dimension.Rows);
            Assert.AreEqual(3, package.Workbook.Worksheets[2].Dimension.Columns);
            
        }
    }
}
